import '@/css/globals.css'
import '@/css/print.css'
import '@/css/prism.css'

import type { Metadata } from 'next'
import { Archivo, IBM_Plex_Mono } from 'next/font/google'
import { Analytics as VercelAnalytics } from '@vercel/analytics/react'
import siteMetadata from '@/data/siteMetadata'
import ThemeScript from '@/components/ThemeScript'
import Footer from '@/components/Footer'
import PikachuCameo from '@/components/PikachuCameo'
import SiteChrome from '@/components/SiteChrome'
import LocalTools from '@/components/LocalTools'
import Parallax from '@/components/Parallax'

const archivo = Archivo({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  display: 'swap',
  variable: '--font-display',
})

const plexMono = IBM_Plex_Mono({
  subsets: ['latin'],
  weight: ['400', '500', '600'],
  display: 'swap',
  variable: '--font-mono',
})

export const metadata: Metadata = {
  metadataBase: new URL(siteMetadata.siteUrl),
  /**
   * The default and the template are deliberately different lengths.
   *
   * The home page gets the full line with the role in it — at 49 characters it
   * fits, and it is the one page where that keyword earns its space. As a
   * suffix on all 60 other pages it cost 52 characters and left 8 for the page
   * title itself, so every single page overflowed what Google will display.
   */
  title: {
    default: siteMetadata.title,
    template: `%s | ${siteMetadata.author}`,
  },
  description: siteMetadata.description,
  openGraph: {
    title: siteMetadata.title,
    description: siteMetadata.description,
    url: './',
    siteName: siteMetadata.title,
    // Named explicitly rather than left to opengraph-image.tsx: the file
    // convention appends a content hash, and LinkedIn shrinks any og:image
    // carrying a query string to a 160px thumbnail. The home page repeats this
    // in its own metadata, since layout metadata loses to the convention file.
    images: [{ url: '/opengraph-image', width: 1200, height: 630 }],
    locale: 'en_US',
    type: 'website',
  },
  alternates: {
    canonical: './',
    types: {
      'application/rss+xml': `${siteMetadata.siteUrl}/feed.xml`,
    },
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  twitter: {
    title: siteMetadata.title,
    description: siteMetadata.description,
    card: 'summary_large_image',
    images: [{ url: '/opengraph-image', width: 1200, height: 630 }],
  },
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang={siteMetadata.language}
      className={`${archivo.variable} ${plexMono.variable}`}
      suppressHydrationWarning
    >
      <head>
        <ThemeScript />
        {/*
         * All generated by `yarn favicons` from the brand mark — see that
         * script for the padding and background the sizes share.
         *
         * /favicon.ico is not declared here: app/favicon.ico is an app-router
         * file convention, so Next emits its own <link> for it. Declaring the
         * copy under /static as well gave two icon URLs for the same bytes,
         * and `sizes="any"` on that one invited browsers to prefer a 48px ICO
         * over the sharper PNGs below.
         *
         * No mask-icon either: safari-pinned-tab.svg is a traced silhouette
         * that is not actually this logo, so Safari was pinning the wrong
         * mark. Modern Safari uses the ordinary favicon anyway.
         */}
        {/* First, and the one most browsers will actually use: it carries both
            colourways and switches on the browser's colour scheme, which is
            what keeps a transparent mark visible on a light tab strip as well
            as a dark one. The PNGs below are the fallback. */}
        <link rel="icon" type="image/svg+xml" href="/static/favicons/favicon.svg" />
        <link rel="icon" type="image/png" sizes="32x32" href="/static/favicons/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/static/favicons/favicon-16x16.png" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/static/favicons/apple-touch-icon-180.png"
        />
        <link rel="manifest" href="/static/favicons/site.webmanifest" />
        <meta name="theme-color" media="(prefers-color-scheme: light)" content="#EDEDEB" />
        <meta name="theme-color" media="(prefers-color-scheme: dark)" content="#000000" />
        <link rel="alternate" type="application/rss+xml" href="/feed.xml" />
      </head>
      <body>
        <a href="#main-content" className="srOnly">
          Skip to main content
        </a>
        {/* Mounted here, not per page: every banded page consumes --par-band,
            so the scroll listener has to run site-wide, not just on home. */}
        <Parallax />
        <main id="main-content">{children}</main>
        <SiteChrome>
          <Footer />
          <PikachuCameo />
          <LocalTools />
        </SiteChrome>
        <VercelAnalytics />
      </body>
    </html>
  )
}
