import { execSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'

function getGitHash() {
  try {
    return execSync('git rev-parse --short HEAD', { encoding: 'utf8' }).trim()
  } catch {
    return ''
  }
}

function getGitCommitDate() {
  try {
    // %cD = RFC 2822, e.g. "Tue, 10 Mar 2026 23:25:08 -0500"
    const raw = execSync('git log -1 --format=%cD', { encoding: 'utf8' }).trim()
    // Shape to "Tue Mar 10 23:25:08 2026 -0500"
    return raw.replace(/^(\w+), (\d+) (\w+) (\d+)(.*)$/, '$1 $3 $2 $4$5')
  } catch {
    return ''
  }
}

const hash = getGitHash()
const date = getGitCommitDate()

const lines = [
  `# Generated by scripts/prebuild-env.mjs - do not commit`,
  `NEXT_PUBLIC_BUILD_HASH=${hash}`,
  `NEXT_PUBLIC_BUILD_DATE=${date}`,
].join('\n')

const envPath = join(process.cwd(), '.env.production.local')
writeFileSync(envPath, lines + '\n', 'utf8')
console.log('Wrote build env:', hash ? `${date} [${hash}]` : '(no git)')
