import { execSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

function getGitHash() {
  try {
    return execSync('git rev-parse --short HEAD', { encoding: 'utf8' }).trim()
  } catch {
    return ''
  }
}

function getGitCommitDate() {
  try {
    // "09/15/2026 12:34:56" — no timezone; the footer is a build marker, not a
    // timestamp anyone needs to convert.
    return execSync("git log -1 --format=%cd --date=format:'%m/%d/%Y %H:%M:%S'", {
      encoding: 'utf8',
    })
      .trim()
      .replace(/^'|'$/g, '')
  } catch {
    return ''
  }
}

const hash = getGitHash()
const date = getGitCommitDate()
// package.json is the single place the version lives; bump it there.
const version = JSON.parse(readFileSync(join(process.cwd(), 'package.json'), 'utf8')).version

const lines = [
  `# Generated by scripts/prebuild-env.mjs - do not commit`,
  `NEXT_PUBLIC_BUILD_HASH=${hash}`,
  `NEXT_PUBLIC_BUILD_DATE=${date}`,
  `NEXT_PUBLIC_BUILD_VERSION=${version}`,
].join('\n')

// Written for development as well as production so the footer stamp is visible
// while working locally. With only the production file the values are absent
// under `next dev` and the footer silently drops to the domain alone. Both
// targets are gitignored, and neither is the hand-managed local config.
const targets = ['production', 'development'].map((mode) =>
  join(process.cwd(), `.env.${mode}.local`)
)

for (const target of targets) {
  writeFileSync(target, lines + '\n', 'utf8')
}

console.log('Wrote build env:', `v${version}`, hash ? `${date} [${hash}]` : '(no git)')
